export declare const ADDRESS_COMPANY = 'ADDRESS_COMPANY';
export declare const ADDRESS_COUNTRY = 'ADDRESS_COUNTRY';
export declare const ADDRESS_COUNTRY_CODE = 'ADDRESS_COUNTRY_CODE';
export declare const ADDRESS_LINE_1 = 'ADDRESS_LINE_1';
export declare const ADDRESS_LINE_2 = 'ADDRESS_LINE_2';
export declare const ADDRESS_PHONE_NUMBER = 'ADDRESS_PHONE_NUMBER';
export declare const ADDRESS_POSTAL_CODE = 'ADDRESS_POSTAL_CODE';
export declare const ADDRESS_REGION = 'ADDRESS_REGION';
export declare const ADDRESS_TOWN = 'ADDRESS_TOWN';
export declare const ADD_TO_CART_LARGE_CTA = 'ADD_TO_CART_LARGE_CTA';
export declare const ADD_TO_CART_SMALL_CTA = 'ADD_TO_CART_SMALL_CTA';
export declare const ADD_TO_CART_TEST = 'ADD_TO_CART_TEST';
export declare const CART_CHECKOUT_CTA = 'CART_CHECKOUT_CTA';
export declare const CART_CLOSE = 'CART_CLOSE';
export declare const CART_HEADING = 'CART_HEADING';
export declare const CART_PROMO_AMOUNT = 'CART_PROMO_AMOUNT';
export declare const CART_PROMO_CTA = 'CART_PROMO_CTA';
export declare const CART_PROMO_INPUT = 'CART_PROMO_INPUT';
export declare const CHECKOUT_BILLING_SAME_SHIPPING =
  'CHECKOUT_BILLING_SAME_SHIPPING';
export declare const CHECKOUT_BILLING_TAX = 'CHECKOUT_BILLING_TAX';
export declare const CHECKOUT_CUSTOMER_EMAIL = 'CHECKOUT_CUSTOMER_EMAIL';
export declare const CHECKOUT_CUSTOMER_FIRST_NAME =
  'CHECKOUT_CUSTOMER_FIRST_NAME';
export declare const CHECKOUT_CUSTOMER_GUEST_BUTTON =
  'CHECKOUT_CUSTOMER_GUEST_BUTTON';
export declare const CHECKOUT_CUSTOMER_LAST_NAME =
  'CHECKOUT_CUSTOMER_LAST_NAME';
export declare const CHECKOUT_CUSTOMER_PASSWORD = 'CHECKOUT_CUSTOMER_PASSWORD';
export declare const CHECKOUT_CUSTOMER_PREFIX = 'CHECKOUT_CUSTOMER_PREFIX';
export declare const CHECKOUT_CUSTOMER_SUBMIT = 'CHECKOUT_CUSTOMER_SUBMIT';
export declare const CHECKOUT_GIFT = 'CHECKOUT_GIFT';
export declare const CHECKOUT_GIFT_INSTRUCTIONS = 'CHECKOUT_GIFT_INSTRUCTIONS';
export declare const CHECKOUT_GIFT_INSTRUCTIONS_CHECKBOX =
  'CHECKOUT_GIFT_INSTRUCTIONS_CHECKBOX';
export declare const CHECKOUT_GIFT_MESSAGE = 'CHECKOUT_GIFT_MESSAGE';
export declare const CHECKOUT_GIFT_MESSAGE_CHECKBOX =
  'CHECKOUT_GIFT_MESSAGE_CHECKBOX';
export declare const CHECKOUT_PAYMENT_CARD = 'CHECKOUT_PAYMENT_CARD';
export declare const CHECKOUT_PAYMENT_CARD_HOLDER =
  'CHECKOUT_PAYMENT_CARD_HOLDER';
export declare const CHECKOUT_PAYMENT_CVC = 'CHECKOUT_PAYMENT_CVC';
export declare const CHECKOUT_PAYMENT_EXPIRATION =
  'CHECKOUT_PAYMENT_EXPIRATION';
export declare const CHECKOUT_PAYMENT_GIFTCARD_CODE =
  'CHECKOUT_PAYMENT_GIFTCARD_CODE';
export declare const CHECKOUT_PAYMENT_GIFTCARD_PIN =
  'CHECKOUT_PAYMENT_GIFTCARD_PIN';
export declare const CHECKOUT_PAYMENT_METHOD = 'CHECKOUT_PAYMENT_METHOD';
export declare const CHECKOUT_PAYMENT_SUBMIT = 'CHECKOUT_PAYMENT_SUBMIT';
export declare const CHECKOUT_REVIEW_SUBMIT = 'CHECKOUT_REVIEW_SUBMIT';
export declare const CHECKOUT_REVIEW_TOS_CHECKBOX =
  'CHECKOUT_REVIEW_TOS_CHECKBOX';
export declare const CHECKOUT_REVIEW_TOTAL = 'CHECKOUT_REVIEW_TOTAL';
export declare const CHECKOUT_SAMPLES_RADIO = 'CHECKOUT_SAMPLES_RADIO';
export declare const CHECKOUT_SAMPLES_SUBMIT = 'CHECKOUT_SAMPLES_SUBMIT';
export declare const CHECKOUT_SHIPPING_METHOD = 'CHECKOUT_SHIPPING_METHOD';
export declare const CHECKOUT_SHIPPING_SUBMIT = 'CHECKOUT_SHIPPING_SUBMIT';
export declare const CONFIRMATION_ACCOUNT_BUTTON =
  'CONFIRMATION_ACCOUNT_BUTTON';
export declare const CONTENT_HUB_LOAD_MORE_BUTTON =
  'CONTENT_HUB_LOAD_MORE_BUTTON';
export declare const FOOTER_LINK = 'FOOTER_LINK';
export declare const NAV_CART = 'NAV_CART';
export declare const NAV_LOGIN = 'NAV_LOGIN';
export declare const NAV_LOGO = 'NAV_LOGO';
export declare const NAV_READ = 'NAV_READ';
export declare const NAV_SEARCH = 'NAV_SEARCH';
export declare const NAV_SHOP = 'NAV_SHOP';
export declare const NAV_SHOP_1 = 'NAV_SHOP_1';
export declare const NAV_SHOP_2 = 'NAV_SHOP_2';
export declare const NAV_SHOP_PRODUCT_CTA = 'NAV_SHOP_PRODUCT_CTA';
export declare const NAV_SHOP_PRODUCT_RADIO = 'NAV_SHOP_PRODUCT_RADIO';
export declare const NAV_VISIT = 'NAV_VISIT';
export declare const NAV_VISIT_CHECKBOX = 'NAV_VISIT_CHECKBOX';
export declare const NAV_VISIT_INPUT = 'NAV_VISIT_INPUT';
