name: Deploy Storybook to GH Pages
on:
  push:
    tags:
      - v*

  workflow_dispatch:

jobs:
  deploy_storybook:
    name: Deploy Storybook
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: actions/setup-node@v2
        with:
          node-version: '14.15.4'

      - name: Store tag name
        run: |
          echo "GEL_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      # to address https://github.com/actions/checkout/issues/13 and
      # https://github.com/tschaub/gh-pages/issues/230#issue-300188493
      - name: Set Git config
        env:
          GITHUB_TOKEN: ${{ secrets.X_GITHUB_TOKEN }}
        run: |
          git config --global user.name "Storybook Deployer"
          git config --global user.email " "
          git remote set-url origin "https://${GITHUB_TOKEN}@github.com/aesop/aesop-gel.git"

      - name: Install
        run: npm ci

      - name: Build Storybook
        run: npm run build-storybook -- --quiet

      - name: Deploy to GH Pages
        run: npm run deploy-storybook -- --message "Update GH Pages to Gel version ${GEL_VERSION}"
