name: On Tag Push
on:
  push:
    tags:
      - v*

env:
  NODE_VERSION: 14.15.4

jobs:
  update_web_ui:
    name: Update Web UI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Store tag name
        run: |
          echo "GEL_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Checkout Web UI
        uses: actions/checkout@v2
        with:
          repository: 'aesop/aesop-web-ui'
          fetch-depth: 1
          ref: 'develop'
          token: ${{ secrets.X_GITHUB_TOKEN }}

      - name: Checkout private tools
        uses: actions/checkout@v2
        with:
          repository: aesop/aesop-github-action
          token: ${{ secrets.X_GITHUB_TOKEN }}
          path: actions

      - name: Update Gel
        uses: ./actions/create-pr
        with:
          TOKEN: ${{ secrets.X_GITHUB_TOKEN }}
          VERSION: ${{ env.GEL_VERSION }}
          CREATE_IN: 'aesop-web-ui'
          BASE_BRANCH: 'develop'

  deploy_storybook:
    name: Deploy Storybook
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Store tag name
        run: |
          echo "GEL_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      # to address https://github.com/actions/checkout/issues/13 and
      # https://github.com/tschaub/gh-pages/issues/230#issue-300188493
      - name: Set Git config
        env:
          GITHUB_TOKEN: ${{ secrets.X_GITHUB_TOKEN }}
        run: |
          git config --global user.name "Storybook Deployer"
          git config --global user.email " "
          git remote set-url origin "https://${GITHUB_TOKEN}@github.com/aesop/aesop-gel.git"

      - name: Install
        run: npm ci

      - name: Deploy to GH Pages
        run: npm run deploy-storybook -- --message "Update GH Pages to Gel version ${GEL_VERSION}"
